name: rpi-dhcp
version: git
summary: DHCP Server for RPI
description: |
  DHCP Server for Raspberry PI

base: core18
confinement: devmode
architectures:
  - build-on: [arm64, amd64]
  - run-on: arm64
#  - build-on: amd64

parts:
  rpi-dhcp:
    plugin: nodejs
    source: .
    build-packages:
      - dirmngr
    stage-packages:
      - nodejs
      - npm

apps:
  rpi-dhcp:
    command: node $SNAP/index.js
    daemon: simple
    restart-condition: always
    plugs: [network-bind]