name: rpi-dhcp
version: git
summary: DHCP Server for RPI
description: |
  DHCP Server for Raspberry PI

base: core18
confinement: devmode

parts:
  rpi-dhcp:
    plugin: nodejs
    source: .
    build-packages:
      - dirmngr
    stage-packages:
      - nodejs
      - npm

apps:
  rpi-dhcp:
    command: bin/node index.js
    daemon: simple
    restart-condition: always
    plugs: [network-bind]